export const data = JSON.parse("{\"key\":\"v-a0cfe9ce\",\"path\":\"/about/website.html\",\"title\":\"关于本站\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"关于本站\",\"shortTitle\":\"关于本站\",\"description\":\"关于本站\",\"icon\":\"fa-solid fa-file-lines\",\"date\":\"2022-12-27T00:00:00.000Z\",\"order\":2,\"article\":false},\"headers\":[{\"level\":2,\"title\":\"网站简介\",\"slug\":\"网站简介\",\"link\":\"#网站简介\",\"children\":[]},{\"level\":2,\"title\":\"心路历程\",\"slug\":\"心路历程\",\"link\":\"#心路历程\",\"children\":[{\"level\":3,\"title\":\"我为什么建这个网站？\",\"slug\":\"我为什么建这个网站\",\"link\":\"#我为什么建这个网站\",\"children\":[]},{\"level\":3,\"title\":\"尝试在线笔记\",\"slug\":\"尝试在线笔记\",\"link\":\"#尝试在线笔记\",\"children\":[]},{\"level\":3,\"title\":\"继续寻找\",\"slug\":\"继续寻找\",\"link\":\"#继续寻找\",\"children\":[]},{\"level\":3,\"title\":\"最终方案\",\"slug\":\"最终方案\",\"link\":\"#最终方案\",\"children\":[]}]},{\"level\":2,\"title\":\"网站定位\",\"slug\":\"网站定位\",\"link\":\"#网站定位\",\"children\":[]},{\"level\":2,\"title\":\"项目初心\",\"slug\":\"项目初心\",\"link\":\"#项目初心\",\"children\":[]},{\"level\":2,\"title\":\"未来愿景\",\"slug\":\"未来愿景\",\"link\":\"#未来愿景\",\"children\":[]},{\"level\":2,\"title\":\"版权协议\",\"slug\":\"版权协议\",\"link\":\"#版权协议\",\"children\":[]},{\"level\":2,\"title\":\"技术支持\",\"slug\":\"技术支持\",\"link\":\"#技术支持\",\"children\":[{\"level\":3,\"title\":\"服务商\",\"slug\":\"服务商\",\"link\":\"#服务商\",\"children\":[]},{\"level\":3,\"title\":\"框架 / 主题\",\"slug\":\"框架-主题\",\"link\":\"#框架-主题\",\"children\":[]},{\"level\":3,\"title\":\"工具\",\"slug\":\"工具\",\"link\":\"#工具\",\"children\":[]}]},{\"level\":2,\"title\":\"仓库连接\",\"slug\":\"仓库连接\",\"link\":\"#仓库连接\",\"children\":[]},{\"level\":2,\"title\":\"网站地址\",\"slug\":\"网站地址\",\"link\":\"#网站地址\",\"children\":[{\"level\":3,\"title\":\"阿里云\",\"slug\":\"阿里云\",\"link\":\"#阿里云\",\"children\":[]},{\"level\":3,\"title\":\"GitHub\",\"slug\":\"github\",\"link\":\"#github\",\"children\":[]},{\"level\":3,\"title\":\"Cloudflare\",\"slug\":\"cloudflare\",\"link\":\"#cloudflare\",\"children\":[]},{\"level\":3,\"title\":\"Netlify\",\"slug\":\"netlify\",\"link\":\"#netlify\",\"children\":[]}]}],\"readingTime\":{\"minutes\":7.22,\"words\":2165},\"filePathRelative\":\"about/website.md\",\"localizedDate\":\"2022年12月27日\",\"excerpt\":\"<h2> 网站简介</h2>\\n<p>本站是 <a href=\\\"/about/me.html\\\" target=\\\"blank\\\">我（攀哥）</a> 搭建的一个个人知识库网站，我也把它叫做 <strong>知识花园</strong><sup class=\\\"footnote-ref\\\"><a href=\\\"#footnote1\\\">[1]</a><a class=\\\"footnote-anchor\\\" id=\\\"footnote-ref1\\\"></a></sup><a class=\\\"footnote-anchor\\\" id=\\\"footnote-ref1\\\"> ，主要包含了我在学习、编程、折腾、创业等几方面的一些笔记或者心得。</a></p>\",\"copyright\":{\"author\":\"杨祖攀\",\"license\":\" CC BY-NC-ND 4.0 \"}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
