export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"fa-solid fa-house","s":"首页"},["/README.md"]],
  ["v-79c1245f","/about/contribution-guide.html",{"y":"p","t":"贡献指南","i":"fa-solid fa-file-lines","O":4,"s":"贡献指南"},[":md"]],
  ["v-53d5aca4","/about/contribution.html",{"y":"p","t":"关于捐助","i":"fa-solid fa-file-lines","O":3,"s":"关于捐助"},[":md"]],
  ["v-5a65fea6","/about/copyright.html",{"y":"p","t":"版权协议","i":"fa-solid fa-file-lines","O":6,"s":"版权协议"},[":md"]],
  ["v-606e3314","/about/error-feedback.html",{"y":"p","t":"错误反馈","i":"fa-solid fa-file-lines","O":5,"s":"错误反馈"},[":md"]],
  ["v-37d2b504","/about/link.html",{"y":"p","t":"友情链接","i":"fa-solid fa-file-lines","O":"09","s":"友情链接"},[":md"]],
  ["v-4274e86f","/about/logs.html",{"y":"p","t":"更新日志","i":"fa-solid fa-file-lines","O":"08","s":"更新日志"},[":md"]],
  ["v-513bdf66","/about/me.html",{"y":"p","t":"关于攀哥","i":"fa-solid fa-file-lines","O":1,"s":"关于攀哥"},[":md"]],
  ["v-5812d768","/about/privacy.html",{"y":"p","t":"隐私政策","i":"fa-solid fa-file-lines","O":7,"s":"隐私政策"},[":md"]],
  ["v-74bc627b","/about/",{"y":"p","t":"关于","i":"fa-solid fa-folder-open","O":12,"s":"关于"},["/about/README.md"]],
  ["v-a0cfe9ce","/about/website.html",{"y":"p","t":"关于本站","i":"fa-solid fa-file-lines","O":2,"s":"关于本站"},[":md"]],
  ["v-bbaa4628","/coding/",{"y":"p","t":"编程","i":"fa-solid fa-folder-open","O":2,"s":"编程"},["/coding/README.md"]],
  ["v-e9eb4950","/career/",{"y":"p","t":"事业","i":"fa-solid fa-folder-open","O":5,"s":"事业"},["/career/README.md"]],
  ["v-149de752","/geek/",{"y":"p","t":"折腾","i":"fa-solid fa-folder-open","O":3,"s":"折腾"},["/geek/README.md"]],
  ["v-14e6315a","/life/",{"y":"p","t":"生活","i":"fa-solid fa-folder-open","O":6,"s":"生活"},["/life/README.md"]],
  ["v-1538da00","/read/",{"y":"p","t":"阅读","i":"fa-solid fa-folder-open","O":1,"s":"阅读"},["/read/README.md"]],
  ["v-c9b48f2e","/write/",{"y":"p","t":"写作","i":"fa-solid fa-folder-open","O":4,"s":"写作"},["/write/README.md"]],
  ["v-cbf736ca","/coding/ai/",{"y":"p","t":"AI","i":"fa-solid fa-folder-open","O":6,"s":"AI"},["/coding/ai/README.md"]],
  ["v-2a88eebc","/coding/back/",{"y":"p","t":"后端","i":"fa-solid fa-folder-open","O":3,"s":"后端"},["/coding/back/README.md"]],
  ["v-269c2f9d","/coding/basis/",{"y":"p","t":"基础","i":"fa-solid fa-folder-open","O":1,"s":"基础"},["/coding/basis/README.md"]],
  ["v-fa8e4c9e","/coding/bigdata/",{"y":"p","t":"大数据","i":"fa-solid fa-folder-open","O":5,"s":"大数据"},["/coding/bigdata/README.md"]],
  ["v-1db69ae6","/coding/devops/",{"y":"p","t":"运维","i":"fa-solid fa-folder-open","O":4,"s":"运维"},["/coding/devops/README.md"]],
  ["v-2e5d6312","/coding/front/",{"y":"p","t":"前端","i":"fa-solid fa-folder-open","O":2,"s":"前端"},["/coding/front/README.md"]],
  ["v-2c8a9084","/geek/cloud-service/",{"y":"p","t":"云服务","i":"fa-solid fa-folder-open","O":3,"s":"云服务"},["/geek/cloud-service/README.md"]],
  ["v-28a10c35","/geek/hardware/",{"y":"p","t":"硬件","i":"fa-solid fa-folder-open","O":1,"s":"硬件"},["/geek/hardware/README.md"]],
  ["v-5335ef54","/geek/software/",{"y":"p","t":"软件","i":"fa-solid fa-folder-open","O":2,"s":"软件"},["/geek/software/README.md"]],
  ["v-f43414fe","/life/apperception/",{"y":"p","t":"感悟","i":"fa-solid fa-folder-open","O":2,"s":"感悟"},["/life/apperception/README.md"]],
  ["v-3a0d8dad","/geek/web/",{"y":"p","t":"Web 服务","i":"fa-solid fa-folder-open","O":4,"s":"Web 服务"},["/geek/web/README.md"]],
  ["v-993bf500","/read/people/",{"y":"p","t":"阅人","i":"fa-solid fa-folder-open","O":2,"s":"阅人"},["/read/people/README.md"]],
  ["v-165a266b","/life/experience/",{"y":"p","t":"经验","i":"fa-solid fa-folder-open","O":1,"s":"经验"},["/life/experience/README.md"]],
  ["v-73d88866","/read/book/",{"y":"p","t":"读书","i":"fa-solid fa-folder-open","O":1,"s":"读书"},["/read/book/README.md"]],
  ["v-258a7301","/read/thing/",{"y":"p","t":"看事","i":"fa-solid fa-folder-open","O":3,"s":"看事"},["/read/thing/README.md"]],
  ["v-711680fc","/read/book/biography/",{"y":"p","t":"名人传记","i":"fa-solid fa-folder-open","O":2,"s":"名人传记"},["/read/book/biography/README.md"]],
  ["v-7176c2c9","/read/book/business/",{"y":"p","t":"商业财经","i":"fa-solid fa-folder-open","O":4,"s":"商业财经"},["/read/book/business/README.md"]],
  ["v-140652a6","/read/book/general/",{"y":"p","t":"通识读物","i":"fa-solid fa-folder-open","O":1,"s":"通识读物"},["/read/book/general/README.md"]],
  ["v-0ba88454","/read/book/grow/",{"y":"p","t":"个人成长","i":"fa-solid fa-folder-open","O":3,"s":"个人成长"},["/read/book/grow/README.md"]],
  ["v-67ad2bb6","/read/book/family/",{"y":"p","t":"亲子家庭","i":"fa-solid fa-folder-open","O":6,"s":"亲子家庭"},["/read/book/family/README.md"]],
  ["v-623474b1","/read/book/science/",{"y":"p","t":"社科新知","i":"fa-solid fa-folder-open","O":7,"s":"社科新知"},["/read/book/science/README.md"]],
  ["v-3ad17081","/read/book/history/",{"y":"p","t":"人文历史","i":"fa-solid fa-folder-open","O":5,"s":"人文历史"},["/read/book/history/README.md"]],
  ["v-590b8705","/read/book/other/",{"y":"p","t":"其他读物","i":"fa-solid fa-folder-open","O":8,"s":"其他读物"},["/read/book/other/README.md"]],
  ["v-b89e1d1a","/read/book/grow/2023001/",{"y":"p","t":"《价值心法》","i":"fa-solid fa-folder-open","O":1,"s":"价值心法"},["/read/book/grow/2023001/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":false},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":false},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":false},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":false},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":false},[]],
]
